project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://kos-danilov.github.io/
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kos-danilov
      - icon: linkedin
        href: https://www.linkedin.com/in/konstantin-danilov-bio/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
execute:
  freeze: auto



